all:
  hosts:
    node1:
      ansible_host: 172.20.0.20
      ip: 172.20.0.20
      access_ip: 172.20.0.20
    node2:
      ansible_host: 172.20.0.21
      ip: 172.20.0.21
      access_ip: 172.20.0.21
    node3:
      ansible_host: 172.20.0.22
      ip: 172.20.0.22
      access_ip: 172.20.0.22
    node4:
      ansible_host: 172.20.0.30
      ip: 172.20.0.30
      access_ip: 172.20.0.30
    node5:
      ansible_host: 172.20.0.31
      ip: 172.20.0.31
      access_ip: 172.20.0.31
    node6:
      ansible_host: 172.20.0.32
      ip: 172.20.0.32
      access_ip: 172.20.0.32
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
        node5:
        node6:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
