all:
  hosts:
    controller-0:
      ansible_host: 172.20.0.20
      ip: 172.20.0.20
      access_ip: 172.20.0.20
    controller-1:
      ansible_host: 172.20.0.21
      ip: 172.20.0.21
      access_ip: 172.20.0.21
    controller-2:
      ansible_host: 172.20.0.22
      ip: 172.20.0.22
      access_ip: 172.20.0.22
    worker-0:
      ansible_host: 172.20.0.30
      ip: 172.20.0.30
      access_ip: 172.20.0.30
    worker-1:
      ansible_host: 172.20.0.31
      ip: 172.20.0.31
      access_ip: 172.20.0.31
    worker-2:
      ansible_host: 172.20.0.32
      ip: 172.20.0.32
      access_ip: 172.20.0.32
  children:
    kube_control_plane:
      hosts:
        controller-0:
        controller-1:
        controller-2:
    kube_node:
      hosts:
        worker-0:
        worker-1:
        worker-2:
    etcd:
      hosts:
        controller-0:
        controller-1:
        controller-2:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
